edition = "2024"
style_edition = "2024"
unstable_features = true

force_explicit_abi = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_macro_bodies = true
format_strings = true
hard_tabs = true
float_literal_trailing_zero = "Always"
imports_indent = "Block"
imports_layout = "HorizontalVertical"
indent_style = "Block"
imports_granularity = "Crate"
match_arm_blocks = true
merge_derives = true
merge_imports = true
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
remove_nested_parens = true
reorder_impl_items = true
reorder_imports = true
group_imports = "StdExternalCrate"
reorder_modules = true
space_after_colon = true
space_before_colon = false
spaces_around_ranges = false
struct_lit_single_line = true
use_field_init_shorthand = true
use_try_shorthand = true
use_small_heuristics = "Off"
wrap_comments = true